name: Processing Build Checker
description: "Builds processing project and creates annotations for any errors"

inputs:
  repo-token:
    description: "The repository token"
    required: true
    default: ${{ github.token }} 
  path-input:
    description: 'Path to the project'
    required: true

runs:
  using: "node16"
  main: "src/index.js"
 
