name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Set this to the version of Node.js that matches your project's requirement

    - name: Install dependencies
      run: npm ci  # This uses the package-lock.json to install exact versions

    - name: Run tests
      run: npm test
      env:
        CI: true
